

#Module declaration

module RandomWord
  def self.random_word
    random_words = %w[
      lemon
      season
      graduation
      cotton
      accordion
      chance
      malady
      thief
      adage
      alligator
      discretion
      volume
      blessing
      unreality
      winter
      mirage
      majority
      blood
      cooperation
      clemency
      ankle
      bagpipe
      horsehair
      irony
      illusion
      camouflage
      animal
      comforter
      interim
      thorn
      physician
      hurdle
      ignorance
      butterfly
      dress
      prisoner
      supplication
      invoice
      revolver
      exertion
      headlight
      heroism
      phantom
      alimony
      promotion
      salad
      pressure
      pepper
      tower
      string
      cradle
      world
      residue
      timepiece
      wistfulness
      northwest
      alcohol
      proxy
      student
      unbeliever
      competition
      artist
      friend
      death
      essence
      caravan
      hindrance
      blossom
      product
      increment
      insolence
      hatred
      wench
      memory
      sensation
      valley
      builder
      master
      machine
      meeting
      shadow
      peach
      edifice
      kerosene
      steerage
      substitute
      moisture
      instructor
      outcome
      mother
      baron
      insect
      comradeship
      attribute
      vegetable
      enterprise
      amplifier
      mastery
      sobriety
      dollar
      officer
      copybook
      method
      hypothesis
      safety
      contribution
      apple
      sunburn
      professor
      lobster
      galaxy
      management
      instrument
      destruction
      pianist
      labyrinth
      nonsense
      mantle
      connoisseur
      originator
      grass
      prestige
      onslaught
      quest
      noose
      robbery
      affection
      gender
      tidbit
      fisherman
      hammer
      brain
      flexibility
      stone
      disposition
      forethought
      feudalism
      leopard
      habitation
      volcano
      painter
      banner
      fault
      dreamer
      examination
      bronze
      vision
      pudding
      daybreak
      exhaustion
      paper
      maker
      moment
      amazement
      antitoxin
      refrigerator
      savant
      pledge
      jeopardy
      utensil
      workhouse
      magazine
      evidence
      criterion
      frontage
      spire
      juggler
      grandmother
      comedy
      venom
      cobblestone
      settler
      franchise
      namesake
      rubble
      occasion
      agility
      kindness
      chief
      emancipation
      lecturer
      disparity
      chair
      fantasy
      honour
      salary
      arbiter
      prairie
      newspaper
      meadow
      casement
      profile
      garden
      geese
      excuse
      woods
      elbow
      plant
      humour
      salutation
      hamlet
      velocity
      gentleman
      inducement
      speech
      metal
      university
      distinction
      courtship
      breast
      inhabitant
      lecture
      miracle
      idiom
      blacksmith
      effort
      colony
      reflex
      mathematics
      cattle
      exclusion
      pupil
      dynasty
      barrel
      tobacco
      thicket
      gravity
      simile
      intimate
      elaboration
      ability
      perjury
      market
      brutality
      water
      glory
      beggar
      garments
      investigation
      metropolis
      chaos
      singer
      lemonade
      democracy
      strawberry
      session
      mucus
      twilight
      sentiment
      pacifism
      background
      poster
      bivouac
      perception
      photograph
      impact
      opinion
      avenue
      author
      cowhide
      palace
      potato
      bouquet
      infant
      instance
      panic
      nymph
      owner
      whalebone
      scarlet
      spree
      gadfly
      decoration
      multiplication
      bullet
      honeycomb
      saloon
      barnacle
      brute
      whale
      vaccination
      animosity
      tripod
      errand
      betrayal
      goblet
      equity
      revolt
      firmament
      garret
      decree
      disaster
      flood
      candy
      lubricant
      street
      friction
      crime
      socialist
      plain
      fatigue
      snake
      cellar
      bereavement
      impropriety
      kerchief
      upkeep
      salute
      headquarters
      stain
      rosin
      mosquito
      detonation
      eccentricity
      damsel
      delirium
      sonata
      portal
      health
      musician
      islander
      surtax
      sunset
      table
      piston
      coast
      creator
      suppression
      citation
      functionary
      capacity
      dream
      vestibule
      reflection
      child
      sadness
      festivity
      exactitude
      jealousy
      truck
      misery
      corpse
      vacuum
      queen
      expression
      nectar
      hound
      genius
      athletics
      pollution
      admiral
      trumpet
      fallacy
      foible
      spinach
      tribute
      dummy
      ambassador
      angle
      bloom
      silence
      interest
      prayer
      pride
      brassiere
      portrait
      sulphur
      committee
      procession
      anxiety
      robber
      institute
      pleasure
      performer
      vanity
      bungalow
      sickness
      assault
      arrow
      heaven
      belief
      steam
      leaflet
      chloride
      truce
      cuisine
      caterpillar
      flesh
      candidate
      length
      virtue
      belfry
      advice
      context
      outsider
      centennial
      building
      blister
      picture
      leggings
      shoes
      determination
      gaiety
      ownership
      ensemble
      forehead
      library
      prosecutor
      weapon
      exhaust
      material
      intellect
      acrobat
      ambulance
      rendezvous
      costume
      odour
      rhapsody
      deduction
      hillside
      cottage
      village
      daffodil
      panorama
      window
      falconer
      derelict
      macaroni
      recital
      welfare
      property
      unification
      infection
      discipline
      evangelist
      priest
      green
      style
      judge
      loyalty
      atmosphere
      ticket
      grief
      research
      devil
      limelight
      satire
      array
      extermination
      poverty
      trellis
      opportunity
      permission
      gallery
      spirit
      molecule
      tendency
      coffee
      anger
      leader
      preview
      freedom
      appliance
      appearance
      recognition
      heredity
      money
      charter
      wholesaler
      diffusion
      bandit
      engagement
      vigour
      diamond
      doctor
      domicile
      victim
      storm
      python
      warbler
      hardwood
      happiness
      underworld
      ocean
      butcher
      yacht
      misconception
      doorman
      banker
      blunderbuss
      steamer
      trouble
      mercy
      square
      history
      offshoot
      answer
      flask
      obedience
      abode
      ]
      random_words.sample
  end
end

puts RandomWord.random_word

